``
{
    "terminal.integrated.defaultProfile.linux": "bash",
    "editor.parameterHints.enabled": false,
    "editor.rulers": [
        80,
        120
    ],
    "editor.fontFamily": "JetBrains Mono",
    "editor.fontLigatures": true,
    "notebook.output.fontFamily": "\"notebook.output.fontFamily\": \"'JetBrains Mono', monospace\"",
    "codeium.enableConfig": {
        "*": false,
        "python": false,
        "markdown": true
    },
    "workbench.iconTheme": "vscode-icons",
    "workbench.activityBar.location": "hidden",
    "explorer.confirmDelete": false,
    "editor.codeLensFontFamily": "Jetbrains Mono",
    "editor.experimentalInlineEdit.fontFamily": "Jetbrains Mono",
    "terminal.integrated.fontFamily": "Jetbrains Mono",
    "vim.highlightedyank.enable": true,
    "vim.useCtrlKeys": false,
    "update.mode": "none",
    "terminal.integrated.smoothScrolling": true,
    "editor.smoothScrolling": true,
    "workbench.list.smoothScrolling": true,
    "window.menuBarVisibility": "toggle",
    "vsicons.dontShowNewVersionMessage": true,
    "code-runner.clearPreviousOutput": true,
    "cSpell.userWords": [
        "apikey",
        "bitboard",
        "bitboards",
        "channelog",
        "DATETIME",
        "dotfiles",
        "ebitda",
        "floorp",
        "ipython",
        "jetbrains",
        "mmclinton",
        "neovim",
        "nextdns",
        "Nixos",
        "nixpkgs",
        "Nums",
        "nvim",
        "pkgs",
        "raycast",
        "reqwest",
        "signup",
        "smci",
        "struct",
        "tenk",
        "tldr",
        "unmarshalling",
        "virtualenv"
    ],
    "errorLens.messageBackgroundMode": "message",
    "errorLens.decorations": {
        "errorRange": {},
        "warningRange": {},
        "infoRange": {},
        "hintRange": {}
    },
    "workbench.sideBar.location": "right",
    "go.toolsManagement.autoUpdate": true,
    "json.schemas": [],
    "workbench.colorTheme": "Dainty – One Dark Pro (chroma 1, lightness 0)",
    "security.workspace.trust.untrustedFiles": "open",
    "cSpell.enableFiletypes": [
        "nix"
    ],
    "editor.minimap.enabled": false,
    "editor.lineNumbers": "relative",
    "rust-analyzer.showUnlinkedFileNotification": false,
    "rust-analyzer.diagnostics.styleLints.enable": true,
    "makefile.configureOnOpen": false,
}
``
